nowo_site_backup_panel:
    resource: ../../Controller/SiteBackupPanelController.php
    type: attribute
    prefix: '%nowo.site_backup.panel.path_prefix%'

nowo_site_backup_setup:
    resource: .
    type: nowo_site_backup_setup
